// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfCheckoutMachine.Data;

#nullable disable

namespace SelfCheckoutMachine.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220329112523_UpdatedCurrenciesTable")]
    partial class UpdatedCurrenciesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SelfCheckoutMachine.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0,
                            CurrencyValue = "5"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0,
                            CurrencyValue = "10"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0,
                            CurrencyValue = "20"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 0,
                            CurrencyValue = "50"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0,
                            CurrencyValue = "100"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 0,
                            CurrencyValue = "200"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 0,
                            CurrencyValue = "500"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 0,
                            CurrencyValue = "1000"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 0,
                            CurrencyValue = "2000"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 0,
                            CurrencyValue = "5000"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 0,
                            CurrencyValue = "10000"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 0,
                            CurrencyValue = "20000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
